name: shop_easy
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  
  flutter_localizations: 
    sdk: flutter
    version: ^0.0.0
  flutter_hooks: ^0.18.5+1
  lottie: ^1.4.1
  flutter_svg: ^1.1.3
  fl_chart: ^0.55.1
  cached_network_image: ^3.2.1
  flutter_credit_card: ^3.0.2
  auto_size_text: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/
    - assets/languages/

